--Cria tabela agendamento
CREATE TABLE AGENDAMENTO (
id_agendamento INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
data_hora timestamp NOT NULL,
motivo VARCHAR(300),
id_paciente integer NOT NULL,
id_veterinario INTEGER NOT NULL,
FOREIGN KEY (id_paciente) REFERENCES PACIENTE (id_paciente),
FOREIGN KEY (id_veterinario) REFERENCES VETERINARIO (id_veterinario)
)

INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-01 10:00:00', 'Consulta de rotina', 1, 1);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-02 11:00:00', 'Vacinação', 2, 2);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-03 12:00:00', 'Exame de sangue', 3, 3);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-04 14:00:00', 'Consulta de emergência', 4, 4);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-05 09:30:00', 'Retorno pós-cirurgia', 5, 5);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-06 15:00:00', 'Check-up geral', 6, 6);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-07 10:30:00', 'Tratamento dental', 7, 7);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-08 16:00:00', 'Consulta de rotina', 8, 8);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-09 09:00:00', 'Vacinação', 9, 9);
INSERT INTO AGENDAMENTO (data_hora, motivo, id_paciente, id_veterinario) VALUES ('2024-09-10 11:15:00', 'Consulta de emergência', 10, 10);

--Cria tabela itens de receita
CREATE TABLE ITENS_RECEITA (
id_item_receita INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
quantidade INTEGER NOT NULL,
dosagem VARCHAR(35),
id_receita integer NOT NULL,
id_medicamento INTEGER NOT NULL,
FOREIGN KEY (id_medicamento) REFERENCES MEDICAMENTO (id_medicamento)
)

INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (1, 5, '1 comprimido por dia', 1);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (1, 3, '1 comprimido a cada 12 horas', 2);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (2, 6, '1 comprimido a cada 8 horas', 3);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (2, 5, '1 dose única', 4);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (3, 2, '1 comprimido a cada 24 horas', 5);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (3, 2, '1 dose a cada 12 horas', 6);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (4, 6, '1 comprimido a cada 8 horas', 7);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (4, 10, '1 dose única', 8);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (5, 7, '1 comprimido por dia', 9);
INSERT INTO ITENS_RECEITA (id_receita, quantidade, dosagem, id_medicamento) VALUES (5, 3, '1 comprimido a cada 24 horas', 10);

--Cria tabela medicamento
CREATE TABLE MEDICAMENTO (
id_medicamento INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
nome VARCHAR(80) NOT NULL,
descricao VARCHAR(370),
preco numeric(10,2)
)

INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Antibiótico A', 'Usado para infecções bacterianas', 50.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Antiinflamatório B', 'Usado para redução de inflamação', 30.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Analgesico C', 'Usado para dor leve a moderada', 15.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Vacina D', 'Vacina para doenças virais', 100.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Antiparasitário E', 'Usado para controle de parasitas', 25.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Suplemento F', 'Suplemento vitamínico', 20.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Calmante G', 'Usado para ansiedade', 40.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Hormônio H', 'Usado para desbalanceamento hormonal', 70.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Antifúngico I', 'Usado para infecções fúngicas', 55.00);
INSERT INTO MEDICAMENTO (nome, descricao, preco) VALUES ('Antiviral J', 'Usado para infecções virais', 80.00);

--Cria tabela paciente
CREATE TABLE PACIENTE (
id_paciente INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
especie VARCHAR(50) NOT NULL,
raca VARCHAR(50),
idade integer,
peso numeric(15,2),
id_tutor INTEGER,
FOREIGN KEY (id_tutor) REFERENCES TUTOR (id_tutor)
)

INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Rex', 'Cão', 'Pit Bull', 5, 25.0, 1);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Mia', 'Gato', 'Siamês', 3, 4.5, 2);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Bobby', 'Cão', 'Labrador', 2, 30.0, 3);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Luna', 'Gato', 'Persa', 4, 5.0, 4);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Max', 'Cão', 'Bulldog', 6, 28.0, 5);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Sophie', 'Gato', 'Sphynx', 1, 3.0, 6);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Jack', 'Cão', 'Beagle', 3, 12.0, 7);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Daisy', 'Gato', 'Maine Coon', 2, 7.0, 8);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Buddy', 'Cão', 'Poodle', 4, 20.0, 9);
INSERT INTO PACIENTE (nome, especie, raca, idade, peso, id_tutor) VALUES ('Bella', 'Gato', 'British Shorthair', 5, 4.0, 10);

--Cria tabela receita
CREATE TABLE RECEITA (
id_receita INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
data_emissao DATE NOT NULL,
id_agendamento INTEGER NOT NULL,
FOREIGN KEY (id_agendamento) REFERENCES AGENDAMENTO (id_agendamento)
)

INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-01', 1);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-02', 2);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-03', 3);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-04', 4);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-05', 5);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-06', 6);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-07', 7);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-08', 8);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-09', 9);
INSERT INTO RECEITA (data, id_agendamento) VALUES ('2024-09-10', 10);

--Cria tabela tutor
CREATE TABLE TUTOR (
id_tutor INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
nome VARCHAR(80) NOT NULL,
endereco VARCHAR(150),
telefone VARCHAR(15),
email VARCHAR(30)
)

INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('João Silva', 'Rua A, 123', '123456789', 'joao@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Maria Oliveira', 'Rua B, 456', '987654321', 'maria@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Carlos Pereira', 'Rua C, 789', '456789123', 'carlos@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Ana Santos', 'Rua D, 101', '321654987', 'ana@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Roberto Costa', 'Rua E, 102', '654321789', 'roberto@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Fernanda Lima', 'Rua F, 103', '789456123', 'fernanda@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Pedro Almeida', 'Rua G, 104', '987321654', 'pedro@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Clara Ferreira', 'Rua H, 105', '159753468', 'clara@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Thiago Rodrigues', 'Rua I, 106', '753159864', 'thiago@email.com');
INSERT INTO TUTOR (nome, endereco, telefone, email) VALUES ('Juliana Martins', 'Rua J, 107', '258147963', 'juliana@email.com');

--Cria tabela veterinario
CREATE TABLE VETERINARIO (
id_veterinario INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
especialidade VARCHAR(100),
telefone VARCHAR(15),
email VARCHAR(100)
)

INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dr. Pedro', 'Cirurgião', '321654987', 'pedro@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dra. Ana', 'Clínica Geral', '654321789', 'ana@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dr. Lucas', 'Dermatologia', '789654123', 'lucas@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dra. Fernanda', 'Cardiologia', '456123789', 'fernanda@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dr. Bruno', 'Oftalmologia', '123789456', 'bruno@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dra. Letícia', 'Odontologia', '987456321', 'leticia@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dr. Tiago', 'Neurologia', '321789654', 'tiago@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dra. Carla', 'Endocrinologia', '654789123', 'carla@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dr. Rafael', 'Ginecologia', '159753852', 'rafael@email.com');
INSERT INTO VETERINARIO (nome, especialidade, telefone, email) VALUES ('Dra. Luana', 'Pediatria', '258963147', 'luana@email.com');